apiVersion: v1
kind: Service
metadata:
  name: fruits-service
spec:
  selector:
    app: fruits
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30808