apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-name
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

# volumes:
#   - name: mypd
#     persistentVolumeClaim:
#       claimName: pvc-name