name: build

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.0.1
      with:
        images: ${{ secrets.DOCKER_USER }}/frutal
        tags: |
          # branch event
          type=ref,event=branch
          # tag event
          type=ref,event=tag

    - name: Build and push Docker image
      env:
        SHORT_SHA: ${GITHUB_SHA::8}
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        build-args: |
          "appVersion=${SHORT_SHA}"
          "commitHash=${GITHUB_SHA}"
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
