name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get build metadata
      id: metadata
      shell: bash
      run: |
        echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
        echo "::set-output name=version::$(git describe --dirty --tags --always)"
    - name: set ldflags env var
      run: echo $LDFLAGS
      env:
        LDFLAGS: "-X main.Version=${{ steps.metadata.outputs.version }} -X main.GitCommit=${{ steps.metadata.outputs.commit }} -X main.BuildDate=${{ steps.metadata.outputs.date }} -s -w"
    - name: Log in to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.0.1
      with:
        images: ${{ secrets.DOCKER_USER }}/frutal
        tags: |
          # branch event
          type=ref,event=branch
          # tag event
          type=ref,event=tag

    - name: Build and push Docker image
      env:
        LDFLAGS: "-X main.Version=${{ steps.metadata.outputs.version }} -X main.GitCommit=${{ steps.metadata.outputs.commit }} -X main.BuildDate=${{ steps.metadata.outputs.date }} -s -w"
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        buid-args: |
          LDFLAGS=${{ env.LDFLAGS }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
